---
- name: Provision Ec2 instance & install XX
  hosts: localhost
  gather_facts: no
  roles:
    - ec2_provision


  tasks: 
    
- name: Configuration of Ec2 instances
  hosts: launched_ec2_instances
  gather_facts: yes
  roles:
    - common
    - frontend
    - backend
