---
# tasks file for frontend
- name: Install frontend dependencies
  become: yes
  npm:
    path: /opt/todo-app/todo-frontend
    state: present

- name: Build frontend
  become: yes 
  command: npm run build   
  args:
    chdir: /opt/todo-app/todo-frontend

- name: Install Pm2 globally
  become: yes 
  npm:
    name: pm2
    global: yes